// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen1;
lv_obj_t *ui_topbar1;
lv_obj_t *ui_title;
lv_obj_t *ui_clock;
lv_obj_t *ui_textmenu;
lv_obj_t *ui_degrees;
lv_obj_t *ui_enviromenttemp;
lv_obj_t *ui_warmtemp;
lv_obj_t *ui_moisttemp;
lv_obj_t *ui_coldtemp;
lv_obj_t *ui_relativehum;
lv_obj_t *ui_relativehum1;
lv_obj_t *ui_relativehum2;
lv_obj_t *ui_relativehum3;
lv_obj_t *ui_relativehum4;
lv_obj_t *ui_back;
lv_obj_t *ui_next;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////
void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Screen1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_topbar1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_topbar1, 480);
lv_obj_set_height( ui_topbar1, 50);
lv_obj_set_align( ui_topbar1, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_topbar1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_topbar1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_topbar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_topbar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_topbar1, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_topbar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_topbar1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_topbar1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_title = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_title, 25 );
lv_obj_set_y( ui_title, 15 );
lv_label_set_text(ui_title,"Resumen");
lv_obj_set_style_text_color(ui_title, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_title, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_title, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_title, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_title, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_title, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_title, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clock = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_clock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clock, -30 );
lv_obj_set_y( ui_clock, 15 );
lv_obj_set_align( ui_clock, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_clock,"21:15");
lv_obj_set_style_text_color(ui_clock, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_clock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_clock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_clock, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_clock, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_clock, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_clock, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_textmenu = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_textmenu, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textmenu, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_textmenu, -120 );
lv_obj_set_y( ui_textmenu, 5 );
lv_obj_set_align( ui_textmenu, LV_ALIGN_CENTER );
lv_label_set_text(ui_textmenu,"Ambiente\nCueva caliente\nCueva humeda\nCueva fria");
lv_obj_set_style_text_color(ui_textmenu, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textmenu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_textmenu, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_textmenu, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_textmenu, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textmenu, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_degrees = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_degrees, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_degrees, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_degrees, 92 );
lv_obj_set_y( ui_degrees, -70 );
lv_obj_set_align( ui_degrees, LV_ALIGN_CENTER );
lv_label_set_text(ui_degrees,"°C");
lv_obj_set_style_text_color(ui_degrees, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_degrees, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_degrees, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_degrees, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_degrees, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_degrees, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_enviromenttemp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_enviromenttemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_enviromenttemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_enviromenttemp, 92 );
lv_obj_set_y( ui_enviromenttemp, -40 );
lv_obj_set_align( ui_enviromenttemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_enviromenttemp,"22.34");
lv_obj_set_style_text_color(ui_enviromenttemp, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_enviromenttemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_enviromenttemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_enviromenttemp, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_enviromenttemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_enviromenttemp, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_warmtemp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_warmtemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_warmtemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_warmtemp, 92 );
lv_obj_set_y( ui_warmtemp, -10 );
lv_obj_set_align( ui_warmtemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_warmtemp,"31.51");
lv_obj_set_style_text_color(ui_warmtemp, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_warmtemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_warmtemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_warmtemp, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_warmtemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_warmtemp, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_moisttemp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_moisttemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_moisttemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_moisttemp, 92 );
lv_obj_set_y( ui_moisttemp, 20 );
lv_obj_set_align( ui_moisttemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_moisttemp,"28.23");
lv_obj_set_style_text_color(ui_moisttemp, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_moisttemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_moisttemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_moisttemp, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_moisttemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_moisttemp, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_coldtemp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_coldtemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_coldtemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_coldtemp, 92 );
lv_obj_set_y( ui_coldtemp, 50 );
lv_obj_set_align( ui_coldtemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_coldtemp,"24.02");
lv_obj_set_style_text_color(ui_coldtemp, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_coldtemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_coldtemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_coldtemp, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_coldtemp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_coldtemp, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_relativehum = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_relativehum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_relativehum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_relativehum, 160 );
lv_obj_set_y( ui_relativehum, -70 );
lv_obj_set_align( ui_relativehum, LV_ALIGN_CENTER );
lv_label_set_text(ui_relativehum,"HR %");
lv_obj_set_style_text_color(ui_relativehum, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_relativehum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_relativehum, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_relativehum, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_relativehum, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_relativehum, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_relativehum1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_relativehum1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_relativehum1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_relativehum1, 160 );
lv_obj_set_y( ui_relativehum1, -40 );
lv_obj_set_align( ui_relativehum1, LV_ALIGN_CENTER );
lv_label_set_text(ui_relativehum1,"56.30");
lv_obj_set_style_text_color(ui_relativehum1, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_relativehum1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_relativehum1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_relativehum1, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_relativehum1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_relativehum1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_relativehum2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_relativehum2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_relativehum2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_relativehum2, 160 );
lv_obj_set_y( ui_relativehum2, -10 );
lv_obj_set_align( ui_relativehum2, LV_ALIGN_CENTER );
lv_label_set_text(ui_relativehum2,"-");
lv_obj_set_style_text_color(ui_relativehum2, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_relativehum2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_relativehum2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_relativehum2, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_relativehum2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_relativehum2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_relativehum3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_relativehum3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_relativehum3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_relativehum3, 160 );
lv_obj_set_y( ui_relativehum3, 20 );
lv_obj_set_align( ui_relativehum3, LV_ALIGN_CENTER );
lv_label_set_text(ui_relativehum3,"60.49");
lv_obj_set_style_text_color(ui_relativehum3, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_relativehum3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_relativehum3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_relativehum3, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_relativehum3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_relativehum3, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_relativehum4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_relativehum4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_relativehum4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_relativehum4, 160 );
lv_obj_set_y( ui_relativehum4, 50 );
lv_obj_set_align( ui_relativehum4, LV_ALIGN_CENTER );
lv_label_set_text(ui_relativehum4,"-");
lv_obj_set_style_text_color(ui_relativehum4, lv_color_hex(0x4E9464), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_relativehum4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_relativehum4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_relativehum4, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_relativehum4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_relativehum4, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_back = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_back, 67);
lv_obj_set_height( ui_back, 26);
lv_obj_set_x( ui_back, 90 );
lv_obj_set_y( ui_back, 133 );
lv_obj_set_align( ui_back, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_back, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_back, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_back, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_back, lv_color_hex(0xCA0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_back, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_next = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_next, 67);
lv_obj_set_height( ui_next, 26);
lv_obj_set_x( ui_next, 160 );
lv_obj_set_y( ui_next, 133 );
lv_obj_set_align( ui_next, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_next, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_next, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_next, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_next, lv_color_hex(0x46BD00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_next, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
