// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_topbar1;
extern lv_obj_t *ui_title;
extern lv_obj_t *ui_clock;
extern lv_obj_t *ui_textmenu;
extern lv_obj_t *ui_degrees;
extern lv_obj_t *ui_enviromenttemp;
extern lv_obj_t *ui_warmtemp;
extern lv_obj_t *ui_moisttemp;
extern lv_obj_t *ui_coldtemp;
extern lv_obj_t *ui_relativehum;
extern lv_obj_t *ui_relativehum1;
extern lv_obj_t *ui_relativehum2;
extern lv_obj_t *ui_relativehum3;
extern lv_obj_t *ui_relativehum4;
extern lv_obj_t *ui_back;
extern lv_obj_t *ui_next;
extern lv_obj_t *ui____initial_actions0;






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
