/**
 * @brief Fichero generado por SquareLine Studio 1.2.3
 * @file ui_events.h
 * @author Jesús Carmelo González Domínguez
 * @date 14-07-2023
*/

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
